kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: pingpong
  name: pingpong
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: index.docker.io/eldarshamukhamedov/pingpong:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 12345
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  type: NodePort
  ports:
  - port: 12345
    protocol: TCP
    name: pingpong
  selector:
    app: pingpong
